 export const serviceCard = [
  {
    title: "Cleaning Services",
    num: "50+ artisans",
    icon: "🧹",
    bg: "bg-yellow-100",
  },
  {
    title: "Plumbing & Water",
    num: "45+ artisans",
    icon: "🔧",
    bg: "bg-blue-100",
  },
  {
    title: "Electrical & Power",
    num: "40+ artisans",
    icon: "⚡",
    bg: "bg-purple-100",
  },
  {
    title: "AC & Appliances",
    num: "35+ artisans",
    icon: "❄️",
    bg: "bg-sky-100",
  },
  {
    title: "Carpentry & Furniture",
    num: "30+ artisans",
    icon: "🪚",
    bg: "bg-lime-100",
  },
  {
    title: "Painting & Decoration",
    num: "35+ artisans",
    icon: "🎨",
    bg: "bg-pink-100",
  },
  {
    title: "Building & Construction",
    num: "40+ artisans",
    icon: "🧱",
    bg: "bg-stone-100",
  },
  {
    title: "Welding & Metalwork",
    num: "25+ artisans",
    icon: "🔩",
    bg: "bg-gray-100",
  },
  {
    title: "Glass & Aluminium",
    num: "20+ artisans",
    icon: "🪟",
    bg: "bg-sky-100",
  },
  {
    title: "Gardening & Landscaping",
    num: "25+ artisans",
    icon: "🌿",
    bg: "bg-teal-100",
  },
  {
    title: "Laundry",
    num: "40+ artisans",
    icon: "🧺",
    bg: "bg-cyan-100",
  },
  {
    title: "Pest Control",
    num: "20+ artisans",
    icon: "🐜",
    bg: "bg-emerald-100",
  },
  {
    title: "Car Wash & Detailing",
    num: "100+ artisans",
    icon: "🚗",
    bg: "bg-green-100",
  },
  {
    title: "Auto Repair",
    num: "50+ artisans",
    icon: "🔧",
    bg: "bg-red-100",
  },
  {
    title: "Moving & Logistics",
    num: "30+ artisans",
    icon: "🚚",
    bg: "bg-amber-100",
  },
  {
    title: "Hair & Beauty",
    num: "75+ artisans",
    icon: "💇‍♀️",
    bg: "bg-rose-100",
  },
  {
    title: "Fashion & Tailoring",
    num: "60+ artisans",
    icon: "👗",
    bg: "bg-red-100",
  },
  {
    title: "Phone & Computer Repair",
    num: "35+ artisans",
    icon: "📱",
    bg: "bg-indigo-100",
  },
  {
    title: "TV & Satellite",
    num: "25+ artisans",
    icon: "📡",
    bg: "bg-blue-100",
  },
  {
    title: "Security Systems",
    num: "20+ artisans",
    icon: "🔐",
    bg: "bg-slate-100",
  },
  {
    title: "Photography & Video",
    num: "40+ artisans",
    icon: "📸",
    bg: "bg-indigo-100",
  },
  {
    title: "Events",
    num: "35+ artisans",
    icon: "🎉",
    bg: "bg-fuchsia-100",
  },
  {
    title: "Food & Catering",
    num: "65+ artisans",
    icon: "🍽️",
    bg: "bg-orange-100",
  },
  {
    title: "Education & Tutoring",
    num: "30+ artisans",
    icon: "📚",
    bg: "bg-violet-100",
  },
  {
    title: "Digital Services",
    num: "25+ artisans",
    icon: "💻",
    bg: "bg-purple-100",
  },
  {
    title: "General Home Services",
    num: "35+ artisans",
    icon: "🛋️",
    bg: "bg-amber-100",
  },
  {
    title: "Outdoor & Recreation",
    num: "15+ artisans",
    icon: "🏊",
    bg: "bg-cyan-100",
  },
];