import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans, Fraunces } from "next/font/google";
import { AppProvider } from "../provider/AppProvider";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Onika",
  description: "Generated by create next app",
};

export const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plus-jakarta",
});

export const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fraunces",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${plusJakartaSans.variable} ${fraunces.variable}`}>
      <body>
        <AppProvider>
          {children}
          <Toaster position="top-right" />
        </AppProvider>
      </body>
    </html>
  );
}
