import type { Metadata } from "next";
import "./globals.css";
import { inter } from "../lib/fonts";
import { AppProvider } from "../provider/AppProvider";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Onika",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {children}
          <Toaster position="top-right" />
        </AppProvider>
      </body>
    </html>
  );
}
